#!/usr/bin/env python3
"""train_timetable 用のダミー時刻表データを生成し V6__seed_timetable.sql を作り直す。

実在のJR時刻表を複製・転記するものではない。station_topology.json に保持しているのは
「どの駅からどの方面へどの行き先の列車が出ているか」という路線網の位置関係（地理的事実）
のみで、これは以前の手動収集データから抽出したもの。発車時刻・番線・列車種別といった
実際のダイヤの中身はすべてこのスクリプトが疑似乱数で新規に生成する。

再現性のため乱数シードは固定（引数で上書き可）。station_topology.json 自体は
Git管理してよいが、生成後の V6__seed_timetable.sql は引き続き .gitignore 対象とする
（Flywayのローカルマイグレーションとして都度このスクリプトで再生成する運用）。

使い方:
    python3 generate_seed.py [seed]
"""
import json
import random
import sys
from pathlib import Path

TOPOLOGY_PATH = Path(__file__).parent / "station_topology.json"
OUTPUT_PATH = Path(__file__).parent.parent / "migrations" / "V6__seed_timetable.sql"

# (列車種別, 始発オフセット上限(分), 発車間隔レンジ(分), 出現に必要な最小行き先数)
# 行き先数が多い方面ほど幹線寄りとみなし、快速系・特急の運行密度を上げる。
TRAIN_TYPES = [
    ("普通", 10, (12, 18), 1),
    ("快速", 15, (20, 30), 2),
    ("新快速", 20, (25, 35), 3),
    ("特急", 40, (90, 150), 4),
]

DAY_START_MIN = 5 * 60       # 5:00
DAY_END_MIN = 24 * 60 + 40   # 終電は日付またぎ 0:40 まで


def sql_escape(s: str) -> str:
    return s.replace("'", "''")


def minutes_to_hhmm(t: int) -> str:
    h = (t // 60) % 24
    m = t % 60
    return f"{h:02d}:{m:02d}"


def generate_departures_for_direction(rng: random.Random, destinations: list[str]):
    """1方面ぶんの一日の発車データ(発車分, 種別, 行き先)のリストを生成する。"""
    departures = []
    for name, start_jitter, (lo, hi), min_dest in TRAIN_TYPES:
        if len(destinations) < min_dest:
            continue
        t = DAY_START_MIN + rng.randint(0, start_jitter)
        while t < DAY_END_MIN:
            dest = rng.choice(destinations)
            departures.append((t, name, dest))
            t += rng.randint(lo, hi)
    departures.sort(key=lambda d: d[0])
    return departures


def main():
    seed = int(sys.argv[1]) if len(sys.argv) > 1 else 20260708
    rng = random.Random(seed)

    with open(TOPOLOGY_PATH, encoding="utf-8") as f:
        topology = json.load(f)

    rows = []
    for station in sorted(topology.keys()):
        for direction, raw_destinations in topology[station].items():
            # 自駅と同名の行き先（元データ由来の表記ゆれ）は除外する
            destinations = [d for d in raw_destinations if d != station] or raw_destinations
            platform_pool = [str(p) for p in range(1, 13)]
            n_platforms = 1 if len(destinations) <= 2 else 2
            platforms = rng.sample(platform_pool, n_platforms)

            for t, train_type, dest in generate_departures_for_direction(rng, destinations):
                platform = rng.choice(platforms)
                rows.append((
                    station,
                    minutes_to_hhmm(t),
                    platform,
                    train_type,
                    dest,
                    direction,
                ))

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
        f.write("-- Auto-generated seed data for train_timetable (synthetic / non-scraped)\n")
        f.write("-- Generated by db/tools/generate_seed.py -- see V6__seed_timetable.sql.README.md\n")
        f.write(
            "INSERT INTO train_timetable "
            "(station_name, osaka_departure_time, osaka_platform, train_type, destination, direction, arrival_status) VALUES\n"
        )
        lines = [
            "('{}', '{}', '{}', '{}', '{}', '{}', '○')".format(
                sql_escape(station), time_str, platform, sql_escape(train_type),
                sql_escape(dest), sql_escape(direction),
            )
            for station, time_str, platform, train_type, dest, direction in rows
        ]
        f.write(",\n".join(lines))
        f.write(";\n")

    print(f"Generated {len(rows)} rows for {len(topology)} stations -> {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
